// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about an unstable default provided by a trait item.
 *
 * Example unstable defaults include:
 * - a stable trait function or method whose body is not stable
 * - a stable trait associated type or const whose default value is not stable
 */
export type ProvidedDefaultUnstable = { 
/**
 * The feature that must be enabled to use the provided default.
 */
feature: string, };
