// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StabilityLevel } from "./StabilityLevel";

/**
 * Stability information for an item.
 *
 * In [`Item::stability`], this refers to regular item stability: whether the item is
 * stable or unstable as represented by the `#[stable]` or `#[unstable]` attributes.
 * In [`Item::const_stability`], this refers to using the item in const contexts,
 * as represented by `#[rustc_const_stable]` or `#[rustc_const_unstable]`.
 */
export type Stability = { 
/**
 * The feature associated with this stability record.
 *
 * For unstable items, this is the feature gate associated with the item.
 * For stable items, this is the historical label recorded when the item was stabilized.
 */
feature: string, level: StabilityLevel, };
