// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StabilityLevel = { "stable": { 
/**
 * The Rust version in which this item became stable, if available.
 */
since: string | null, } } | "unstable";
